services:
  backend:
    image: reinsaemani/ecommerce-backend:v1.0.54
    container_name: e-commerce-backend
    ports:
      - "5050:5050"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: pnpm start
    networks:
      - e-commerce-net

  db:
    image: mysql:8
    container_name: e-commerce-db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u test -ptest"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - e-commerce-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
      - node-exporter
    networks:
      - e-commerce-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    env_file:
      - .env
    networks:
      - e-commerce-net

  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /var/lib/node_exporter/textfile_collector:/var/lib/node_exporter/textfile_collector
    command:
      - --collector.textfile.directory=/var/lib/node_exporter/textfile_collector
    networks:
      - e-commerce-net

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.generated.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - e-commerce-net

volumes:
  mysql_data:
  grafana_data:

networks:
  e-commerce-net:
    driver: bridge