apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: e-commerce-backend:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5050
          env:
            - name: APP_ENV
              value: "development"
            - name: DATABASE_HOST
              value: "db"
            - name: DATABASE_USER
              value: "test"
            - name: DATABASE_PASSWORD
              value: "test"
            - name: DATABASE_NAME
              value: "ecommerce"
            - name: DATABASE_PORT
              value: "3306"
            - name: PORT
              value: "5050"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_URL

          # ✅ HEALTH CHECK (WAJIB)
          livenessProbe:
            httpGet:
              path: /health
              port: 5050
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3

          # ✅ READY CHECK (BIAR TRAFFIC TIDAK MASUK TERLALU CEPAT)
          readinessProbe:
            httpGet:
              path: /health
              port: 5050
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3