apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: prod
spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      initContainers:
        - name: wait-db
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Waiting for DB..."
              until nc -z db 3306; do
                sleep 2
              done

      containers:
        - name: migrate
          image: reinsaemani/ecommerce-backend:latest
          imagePullPolicy: Always

          command: ["pnpm"]
          args: ["prisma", "migrate", "deploy"]

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_URL