apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: reinsaemani/ecommerce-backend:v1.0.74
          imagePullPolicy: Always
          ports:
            - containerPort: 5050

          env:
            - name: APP_ENV
              value: "production"
            - name: DATABASE_HOST
              value: "db"
            - name: DATABASE_USER
              value: "test"
            - name: DATABASE_PASSWORD
              value: "test"
            - name: DATABASE_NAME
              value: "ecommerce"
            - name: DATABASE_PORT
              value: "3306"  
            - name: PORT
              value: "5050"
            - name: DATABASE_URL
              value: "mysql://test:test@db:3306/ecommerce"

          livenessProbe:
            httpGet:
              path: /health
              port: 5050
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5050
            initialDelaySeconds: 5
            periodSeconds: 5