name: Kubernetes CI/CD

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  workflow_dispatch:

env:
  IMAGE: ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend

jobs:

# =========================
# BUILD (MAIN + TAG)
# =========================
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push latest + sha
        run: |
          docker build -f Dockerfile.prod -t $IMAGE:latest .
          docker tag $IMAGE:latest $IMAGE:${GITHUB_SHA}
          docker push $IMAGE:latest
          docker push $IMAGE:${GITHUB_SHA}

      - name: Build TAG version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker tag $IMAGE:latest $IMAGE:${GITHUB_REF_NAME}
          docker push $IMAGE:${GITHUB_REF_NAME}

# =========================
# DEPLOY STAGING (MAIN ONLY)
# =========================
  deploy-staging:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Deploy staging
        run: |
          kubectl apply -f k8s/staging/
          kubectl set image deployment/backend backend=$IMAGE:latest -n staging
          kubectl rollout status deployment/backend -n staging --timeout=180s

# =========================
# DEPLOY PROD (TAG ONLY)
# =========================
  deploy-prod:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Deploy prod
        run: |
          kubectl apply -f k8s/prod/
          kubectl set image deployment/backend backend=$IMAGE:${GITHUB_REF_NAME} -n prod
          kubectl rollout status deployment/backend -n prod --timeout=180s