name: Kubernetes CI/CD

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  workflow_dispatch:

env:
  IMAGE: ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend

jobs:

# =========================
# BUILD (ONLY MAIN)
# =========================
  build:
    if: github.ref_type != 'tag'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.prod
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}

# =========================
# DEPLOY STAGING (MAIN ONLY)
# =========================
  deploy-staging:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Apply Staging
        run: |
          kubectl apply -n staging -f k8s/staging/
          kubectl set image deployment/backend backend=${{ env.IMAGE }}:latest -n staging
          kubectl rollout status deployment/backend -n staging --timeout=180s

# =========================
# RELEASE (TAG ONLY)
# =========================
  release:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull latest
        run: docker pull $IMAGE:latest

      - name: Tag version
        run: docker tag $IMAGE:latest $IMAGE:${{ github.ref_name }}

      - name: Push version
        run: docker push $IMAGE:${{ github.ref_name }}

# =========================
# DEPLOY PROD (TAG ONLY)
# =========================
  deploy-prod:
    if: github.ref_type == 'tag'
    needs: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Apply Prod
        run: |
          kubectl apply -f k8s/prod/
          kubectl set image deployment/backend backend=${{ env.IMAGE }}:${{ github.ref_name }} -n prod
          kubectl rollout status deployment/backend -n prod --timeout=180s